//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 03:06:41 PM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.mapping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{mapping.model.servicesapi.cmsadapter.stanbol.apache.org}ConceptBridge"/>
 *         &lt;element ref="{mapping.model.servicesapi.cmsadapter.stanbol.apache.org}SubsumptionBridge"/>
 *         &lt;element ref="{mapping.model.servicesapi.cmsadapter.stanbol.apache.org}PropertyBridge"/>
 *         &lt;element ref="{mapping.model.servicesapi.cmsadapter.stanbol.apache.org}InstanceBridge"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "conceptBridgeOrSubsumptionBridgeOrPropertyBridge"
})
@XmlRootElement(name = "BridgeDefinitions")
public class BridgeDefinitions {

    @XmlElements({
        @XmlElement(name = "SubsumptionBridge", type = SubsumptionBridge.class),
        @XmlElement(name = "ConceptBridge", type = ConceptBridge.class),
        @XmlElement(name = "PropertyBridge", type = PropertyBridge.class),
        @XmlElement(name = "InstanceBridge", type = InstanceBridge.class)
    })
    protected List<Object> conceptBridgeOrSubsumptionBridgeOrPropertyBridge;

    /**
     * Gets the value of the conceptBridgeOrSubsumptionBridgeOrPropertyBridge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conceptBridgeOrSubsumptionBridgeOrPropertyBridge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConceptBridgeOrSubsumptionBridgeOrPropertyBridge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubsumptionBridge }
     * {@link ConceptBridge }
     * {@link PropertyBridge }
     * {@link InstanceBridge }
     * 
     * 
     */
    public List<Object> getConceptBridgeOrSubsumptionBridgeOrPropertyBridge() {
        if (conceptBridgeOrSubsumptionBridgeOrPropertyBridge == null) {
            conceptBridgeOrSubsumptionBridgeOrPropertyBridge = new ArrayList<Object>();
        }
        return this.conceptBridgeOrSubsumptionBridgeOrPropertyBridge;
    }

}
