/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.09 at 02:52:53 PM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.mapping;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.stanbol.cmsadapter.servicesapi.model.mapping package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.stanbol.cmsadapter.servicesapi.model.mapping
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InstanceBridge }
     * 
     */
    public InstanceBridge createInstanceBridge() {
        return new InstanceBridge();
    }

    /**
     * Create an instance of {@link PropertyBridge }
     * 
     */
    public PropertyBridge createPropertyBridge() {
        return new PropertyBridge();
    }

    /**
     * Create an instance of {@link PropertyAnnotation }
     * 
     */
    public PropertyAnnotation createPropertyAnnotation() {
        return new PropertyAnnotation();
    }

    /**
     * Create an instance of {@link ConceptBridge }
     * 
     */
    public ConceptBridge createConceptBridge() {
        return new ConceptBridge();
    }

    /**
     * Create an instance of {@link SubsumptionBridge }
     * 
     */
    public SubsumptionBridge createSubsumptionBridge() {
        return new SubsumptionBridge();
    }

    /**
     * Create an instance of {@link BridgeDefinitions }
     * 
     */
    public BridgeDefinitions createBridgeDefinitions() {
        return new BridgeDefinitions();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

}
