//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 03:06:41 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "mapping.model.servicesapi.cmsadapter.stanbol.apache.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.apache.stanbol.cmsadapter.servicesapi.model.mapping;
