//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.06 at 01:54:21 PM EEST 
//

package org.apache.stanbol.ontologymanager.store.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{model.rest.persistence.iks.srdc.com.tr}ClassMetaInformation"/>
 *         &lt;element ref="{model.rest.persistence.iks.srdc.com.tr}BuiltInResource"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"classMetaInformationOrBuiltInResource"})
@XmlRootElement(name = "Domain")
public class Domain {

    @XmlElements({@XmlElement(name = "ClassMetaInformation", type = ClassMetaInformation.class),
                  @XmlElement(name = "BuiltInResource", type = BuiltInResource.class)})
    protected List<Object> classMetaInformationOrBuiltInResource;

    /**
     * Gets the value of the classMetaInformationOrBuiltInResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification
     * you make to the returned list will be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the classMetaInformationOrBuiltInResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getClassMetaInformationOrBuiltInResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ClassMetaInformation }
     * {@link BuiltInResource }
     * 
     * 
     */
    public List<Object> getClassMetaInformationOrBuiltInResource() {
        if (classMetaInformationOrBuiltInResource == null) {
            classMetaInformationOrBuiltInResource = new ArrayList<Object>();
        }
        return this.classMetaInformationOrBuiltInResource;
    }

}
