/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.13 at 09:50:16 AM EEST 
//

package org.apache.stanbol.ontologymanager.store.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{model.rest.persistence.iks.srdc.com.tr}IndividualMetaInformation"/>
 *         &lt;element ref="{model.rest.persistence.iks.srdc.com.tr}ContainerClasses"/>
 *         &lt;element ref="{model.rest.persistence.iks.srdc.com.tr}PropertyAssertions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"individualMetaInformation", "containerClasses", "propertyAssertions"})
@XmlRootElement(name = "IndividualContext")
public class IndividualContext {

    @XmlElement(name = "IndividualMetaInformation", required = true)
    protected IndividualMetaInformation individualMetaInformation;
    @XmlElement(name = "ContainerClasses", required = true)
    protected ContainerClasses containerClasses;
    @XmlElement(name = "PropertyAssertions", required = true)
    protected PropertyAssertions propertyAssertions;

    /**
     * Gets the value of the individualMetaInformation property.
     * 
     * @return possible object is {@link IndividualMetaInformation }
     * 
     */
    public IndividualMetaInformation getIndividualMetaInformation() {
        return individualMetaInformation;
    }

    /**
     * Sets the value of the individualMetaInformation property.
     * 
     * @param value
     *            allowed object is {@link IndividualMetaInformation }
     * 
     */
    public void setIndividualMetaInformation(IndividualMetaInformation value) {
        this.individualMetaInformation = value;
    }

    /**
     * Gets the value of the containerClasses property.
     * 
     * @return possible object is {@link ContainerClasses }
     * 
     */
    public ContainerClasses getContainerClasses() {
        return containerClasses;
    }

    /**
     * Sets the value of the containerClasses property.
     * 
     * @param value
     *            allowed object is {@link ContainerClasses }
     * 
     */
    public void setContainerClasses(ContainerClasses value) {
        this.containerClasses = value;
    }

    /**
     * Gets the value of the propertyAssertions property.
     * 
     * @return possible object is {@link PropertyAssertions }
     * 
     */
    public PropertyAssertions getPropertyAssertions() {
        return propertyAssertions;
    }

    /**
     * Sets the value of the propertyAssertions property.
     * 
     * @param value
     *            allowed object is {@link PropertyAssertions }
     * 
     */
    public void setPropertyAssertions(PropertyAssertions value) {
        this.propertyAssertions = value;
    }

}
