/* Generated By:JavaCC: Do not edit this line. KReSRuleParserConstants.java */
package eu.iksproject.kres.rules.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KReSRuleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LARROW = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int EQUAL = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int SAME = 10;
  /** RegularExpression Id. */
  int DIFFERENT = 11;
  /** RegularExpression Id. */
  int IS = 12;
  /** RegularExpression Id. */
  int HAS = 13;
  /** RegularExpression Id. */
  int RANGE = 14;
  /** RegularExpression Id. */
  int VALUES = 15;
  /** RegularExpression Id. */
  int LPAR = 16;
  /** RegularExpression Id. */
  int RPAR = 17;
  /** RegularExpression Id. */
  int DQUOT = 18;
  /** RegularExpression Id. */
  int LQUAD = 19;
  /** RegularExpression Id. */
  int RQUAD = 20;
  /** RegularExpression Id. */
  int NUM = 21;
  /** RegularExpression Id. */
  int VAR = 22;
  /** RegularExpression Id. */
  int VARIABLE = 23;
  /** RegularExpression Id. */
  int URI = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"->\"",
    "\":\"",
    "\"=\"",
    "\".\"",
    "\",\"",
    "\"same\"",
    "\"different\"",
    "\"is\"",
    "\"has\"",
    "\"range\"",
    "\"values\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "<NUM>",
    "<VAR>",
    "<VARIABLE>",
    "<URI>",
  };

}
