/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
/* Generated By:JavaCC: Do not edit this line. RuleParserConstants.java */
package org.apache.stanbol.rules.manager.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RuleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LARROW = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int EQUAL = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int REFLEXIVE = 10;
  /** RegularExpression Id. */
  int SAME = 11;
  /** RegularExpression Id. */
  int DIFFERENT = 12;
  /** RegularExpression Id. */
  int LESSTHAN = 13;
  /** RegularExpression Id. */
  int GREATERTHAN = 14;
  /** RegularExpression Id. */
  int IS = 15;
  /** RegularExpression Id. */
  int NEW_NODE = 16;
  /** RegularExpression Id. */
  int LENGTH = 17;
  /** RegularExpression Id. */
  int SUBSTRING = 18;
  /** RegularExpression Id. */
  int UPPERCASE = 19;
  /** RegularExpression Id. */
  int LOWERCASE = 20;
  /** RegularExpression Id. */
  int STARTS_WITH = 21;
  /** RegularExpression Id. */
  int ENDS_WITH = 22;
  /** RegularExpression Id. */
  int LET = 23;
  /** RegularExpression Id. */
  int CONCAT = 24;
  /** RegularExpression Id. */
  int HAS = 25;
  /** RegularExpression Id. */
  int VALUES = 26;
  /** RegularExpression Id. */
  int NOTEX = 27;
  /** RegularExpression Id. */
  int PLUS = 28;
  /** RegularExpression Id. */
  int MINUS = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int NAMESPACE = 31;
  /** RegularExpression Id. */
  int LOCALNAME = 32;
  /** RegularExpression Id. */
  int STR = 33;
  /** RegularExpression Id. */
  int APOX = 34;
  /** RegularExpression Id. */
  int UNION = 35;
  /** RegularExpression Id. */
  int CREATE_LABEL = 36;
  /** RegularExpression Id. */
  int SPARQL_C = 37;
  /** RegularExpression Id. */
  int SPARQL_D = 38;
  /** RegularExpression Id. */
  int SPARQL_DD = 39;
  /** RegularExpression Id. */
  int PROP = 40;
  /** RegularExpression Id. */
  int IS_BLANK = 41;
  /** RegularExpression Id. */
  int FORWARD_CHAIN = 42;
  /** RegularExpression Id. */
  int LPAR = 43;
  /** RegularExpression Id. */
  int RPAR = 44;
  /** RegularExpression Id. */
  int DQUOT = 45;
  /** RegularExpression Id. */
  int LQUAD = 46;
  /** RegularExpression Id. */
  int RQUAD = 47;
  /** RegularExpression Id. */
  int NUM = 48;
  /** RegularExpression Id. */
  int VAR = 49;
  /** RegularExpression Id. */
  int VARIABLE = 50;
  /** RegularExpression Id. */
  int URI = 51;
  /** RegularExpression Id. */
  int STRING = 52;
  /** RegularExpression Id. */
  int SPARQL_STRING = 53;
  /** RegularExpression Id. */
  int BNODE = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"->\"",
    "\":\"",
    "\"=\"",
    "\".\"",
    "\",\"",
    "\"+\"",
    "\"same\"",
    "\"different\"",
    "\"lt\"",
    "\"gt\"",
    "\"is\"",
    "\"newNode\"",
    "\"length\"",
    "\"substring\"",
    "\"upperCase\"",
    "\"lowerCase\"",
    "\"startsWith\"",
    "\"endsWith\"",
    "\"let\"",
    "\"concat\"",
    "\"has\"",
    "\"values\"",
    "\"notex\"",
    "\"sum\"",
    "\"sub\"",
    "\"not\"",
    "\"namespace\"",
    "\"localname\"",
    "\"str\"",
    "\"^\"",
    "\"union\"",
    "\"createLabel\"",
    "\"sparql-c\"",
    "\"sparql-d\"",
    "\"sparql-dd\"",
    "\"prop\"",
    "\"isBlank\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "<NUM>",
    "<VAR>",
    "<VARIABLE>",
    "<URI>",
    "<STRING>",
    "<SPARQL_STRING>",
    "<BNODE>",
  };

}
