//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 11:44:48 AM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.web;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element was created to use object types as a
 * 				list in general, regardless of being a content or classification
 * 				object.  
 * 			
 * 
 * <p>Java class for CMSObjects element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="CMSObjects">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="CMSObject" type="{web.model.servicesapi.cmsadapter.stanbol.apache.org}CMSObject" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cmsObject"
})
@XmlRootElement(name = "CMSObjects")
public class CMSObjects {

    @XmlElement(name = "CMSObject", namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected List<CMSObject> cmsObject;

    /**
     * Gets the value of the cmsObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cmsObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCMSObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CMSObject }
     * 
     * 
     */
    public List<CMSObject> getCMSObject() {
        if (cmsObject == null) {
            cmsObject = new ArrayList<CMSObject>();
        }
        return this.cmsObject;
    }

}
