//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 11:44:48 AM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.web;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * defines repository paramaters
 * 
 * <p>Java class for connectionInfo element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="connectionInfo">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}repositoryURL"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}workspaceName"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}username"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}password"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}connectionType"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}ontologyURI"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "repositoryURL",
    "workspaceName",
    "username",
    "password",
    "connectionType",
    "ontologyURI"
})
@XmlRootElement(name = "connectionInfo")
public class ConnectionInfo {

    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String repositoryURL;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String workspaceName;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String username;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String password;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String connectionType;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String ontologyURI;

    /**
     * Gets the value of the repositoryURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepositoryURL() {
        return repositoryURL;
    }

    /**
     * Sets the value of the repositoryURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepositoryURL(String value) {
        this.repositoryURL = value;
    }

    /**
     * Gets the value of the workspaceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkspaceName() {
        return workspaceName;
    }

    /**
     * Sets the value of the workspaceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkspaceName(String value) {
        this.workspaceName = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the connectionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionType() {
        return connectionType;
    }

    /**
     * Sets the value of the connectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionType(String value) {
        this.connectionType = value;
    }

    /**
     * Gets the value of the ontologyURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntologyURI() {
        return ontologyURI;
    }

    /**
     * Sets the value of the ontologyURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntologyURI(String value) {
        this.ontologyURI = value;
    }

}
