/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 10:53:39 AM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.web;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.stanbol.cmsadapter.servicesapi.model.web package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Namespace_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "namespace");
    private final static QName _UniqueRef_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "uniqueRef");
    private final static QName _ContainerObjectRef_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "containerObjectRef");
    private final static QName _ContentObject_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "contentObject");
    private final static QName _Password_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "password");
    private final static QName _Localname_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "localname");
    private final static QName _ConnectionType_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "connectionType");
    private final static QName _ClassificationObject_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "classificationObject");
    private final static QName _ValueConstraint_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "valueConstraint");
    private final static QName _AllowedObjectTypeDefRef_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "allowedObjectTypeDefRef");
    private final static QName _ParentRef_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "parentRef");
    private final static QName _ObjectTypeRef_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "objectTypeRef");
    private final static QName _OntologyURI_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "ontologyURI");
    private final static QName _WorkspaceName_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "workspaceName");
    private final static QName _Cardinality_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "cardinality");
    private final static QName _Required_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "required");
    private final static QName _Value_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "value");
    private final static QName _Path_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "path");
    private final static QName _SourceObjectTypeRef_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "sourceObjectTypeRef");
    private final static QName _RepositoryURL_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "repositoryURL");
    private final static QName _PropertyType_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "propertyType");
    private final static QName _Username_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "username");
    private final static QName _Annotation_QNAME = new QName("web.model.servicesapi.cmsadapter.stanbol.apache.org", "annotation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.stanbol.cmsadapter.servicesapi.model.web
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObjectTypeDefinition }
     * 
     */
    public ObjectTypeDefinition createObjectTypeDefinition() {
        return new ObjectTypeDefinition();
    }

    /**
     * Create an instance of {@link PropertyDefinition }
     * 
     */
    public PropertyDefinition createPropertyDefinition() {
        return new PropertyDefinition();
    }

    /**
     * Create an instance of {@link PropertySemantics }
     * 
     */
    public PropertySemantics createPropertySemantics() {
        return new PropertySemantics();
    }

    /**
     * Create an instance of {@link PropertyAnnotation }
     * 
     */
    public PropertyAnnotation createPropertyAnnotation() {
        return new PropertyAnnotation();
    }

    /**
     * Create an instance of {@link ObjectTypeDefinitions }
     * 
     */
    public ObjectTypeDefinitions createObjectTypeDefinitions() {
        return new ObjectTypeDefinitions();
    }

    /**
     * Create an instance of {@link ConnectionInfo }
     * 
     */
    public ConnectionInfo createConnectionInfo() {
        return new ConnectionInfo();
    }

    /**
     * Create an instance of {@link ClassificationObject }
     * 
     */
    public ClassificationObject createClassificationObject() {
        return new ClassificationObject();
    }

    /**
     * Create an instance of {@link CMSObjects }
     * 
     */
    public CMSObjects createCMSObjects() {
        return new CMSObjects();
    }

    /**
     * Create an instance of {@link ContentObject }
     * 
     */
    public ContentObject createContentObject() {
        return new ContentObject();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link CMSObject }
     * 
     */
    public CMSObject createCMSObject() {
        return new CMSObject();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "namespace")
    public JAXBElement<String> createNamespace(String value) {
        return new JAXBElement<String>(_Namespace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "uniqueRef")
    public JAXBElement<String> createUniqueRef(String value) {
        return new JAXBElement<String>(_UniqueRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "containerObjectRef")
    public JAXBElement<String> createContainerObjectRef(String value) {
        return new JAXBElement<String>(_ContainerObjectRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "contentObject")
    public JAXBElement<ContentObject> createContentObject(ContentObject value) {
        return new JAXBElement<ContentObject>(_ContentObject_QNAME, ContentObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "password")
    public JAXBElement<String> createPassword(String value) {
        return new JAXBElement<String>(_Password_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "localname")
    public JAXBElement<String> createLocalname(String value) {
        return new JAXBElement<String>(_Localname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "connectionType")
    public JAXBElement<String> createConnectionType(String value) {
        return new JAXBElement<String>(_ConnectionType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassificationObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "classificationObject")
    public JAXBElement<ClassificationObject> createClassificationObject(ClassificationObject value) {
        return new JAXBElement<ClassificationObject>(_ClassificationObject_QNAME, ClassificationObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "valueConstraint")
    public JAXBElement<String> createValueConstraint(String value) {
        return new JAXBElement<String>(_ValueConstraint_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "allowedObjectTypeDefRef")
    public JAXBElement<String> createAllowedObjectTypeDefRef(String value) {
        return new JAXBElement<String>(_AllowedObjectTypeDefRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "parentRef")
    public JAXBElement<String> createParentRef(String value) {
        return new JAXBElement<String>(_ParentRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "objectTypeRef")
    public JAXBElement<String> createObjectTypeRef(String value) {
        return new JAXBElement<String>(_ObjectTypeRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "ontologyURI")
    public JAXBElement<String> createOntologyURI(String value) {
        return new JAXBElement<String>(_OntologyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "workspaceName")
    public JAXBElement<String> createWorkspaceName(String value) {
        return new JAXBElement<String>(_WorkspaceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "cardinality")
    public JAXBElement<BigInteger> createCardinality(BigInteger value) {
        return new JAXBElement<BigInteger>(_Cardinality_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "required")
    public JAXBElement<Boolean> createRequired(Boolean value) {
        return new JAXBElement<Boolean>(_Required_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "path")
    public JAXBElement<String> createPath(String value) {
        return new JAXBElement<String>(_Path_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "sourceObjectTypeRef")
    public JAXBElement<String> createSourceObjectTypeRef(String value) {
        return new JAXBElement<String>(_SourceObjectTypeRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "repositoryURL")
    public JAXBElement<String> createRepositoryURL(String value) {
        return new JAXBElement<String>(_RepositoryURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "propertyType")
    public JAXBElement<PropType> createPropertyType(PropType value) {
        return new JAXBElement<PropType>(_PropertyType_QNAME, PropType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "username")
    public JAXBElement<String> createUsername(String value) {
        return new JAXBElement<String>(_Username_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", name = "annotation")
    public JAXBElement<AnnotationType> createAnnotation(AnnotationType value) {
        return new JAXBElement<AnnotationType>(_Annotation_QNAME, AnnotationType.class, null, value);
    }

}
