//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 11:44:48 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org")
package org.apache.stanbol.cmsadapter.servicesapi.model.web;
