//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 11:44:48 AM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.web;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propertyDefinition element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="propertyDefinition">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}sourceObjectTypeRef" minOccurs="0"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}localname"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}namespace" minOccurs="0"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}uniqueRef"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}propertyType"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}cardinality" minOccurs="0"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}required" minOccurs="0"/>
 *           &lt;sequence>
 *             &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}valueConstraint" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}annotation" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceObjectTypeRef",
    "localname",
    "namespace",
    "uniqueRef",
    "propertyType",
    "cardinality",
    "required",
    "valueConstraint",
    "annotation"
})
@XmlRootElement(name = "propertyDefinition")
public class PropertyDefinition {

    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org")
    protected String sourceObjectTypeRef;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String localname;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org")
    protected String namespace;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String uniqueRef;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected PropType propertyType;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org")
    protected BigInteger cardinality;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org")
    protected Boolean required;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected List<String> valueConstraint;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org")
    protected AnnotationType annotation;

    /**
     * Gets the value of the sourceObjectTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceObjectTypeRef() {
        return sourceObjectTypeRef;
    }

    /**
     * Sets the value of the sourceObjectTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceObjectTypeRef(String value) {
        this.sourceObjectTypeRef = value;
    }

    /**
     * Gets the value of the localname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalname() {
        return localname;
    }

    /**
     * Sets the value of the localname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalname(String value) {
        this.localname = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the uniqueRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueRef() {
        return uniqueRef;
    }

    /**
     * Sets the value of the uniqueRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueRef(String value) {
        this.uniqueRef = value;
    }

    /**
     * Gets the value of the propertyType property.
     * 
     * @return
     *     possible object is
     *     {@link PropType }
     *     
     */
    public PropType getPropertyType() {
        return propertyType;
    }

    /**
     * Sets the value of the propertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropType }
     *     
     */
    public void setPropertyType(PropType value) {
        this.propertyType = value;
    }

    /**
     * Gets the value of the cardinality property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCardinality(BigInteger value) {
        this.cardinality = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the valueConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValueConstraint() {
        if (valueConstraint == null) {
            valueConstraint = new ArrayList<String>();
        }
        return this.valueConstraint;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationType }
     *     
     */
    public AnnotationType getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationType }
     *     
     */
    public void setAnnotation(AnnotationType value) {
        this.annotation = value;
    }

}
