//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 11:44:48 AM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.web;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propertyAnnotation element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="propertyAnnotation">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}uniqueRef"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}annotation"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueRef",
    "annotation"
})
@XmlRootElement(name = "propertyAnnotation")
public class PropertyAnnotation {

    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String uniqueRef;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected AnnotationType annotation;

    /**
     * Gets the value of the uniqueRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueRef() {
        return uniqueRef;
    }

    /**
     * Sets the value of the uniqueRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueRef(String value) {
        this.uniqueRef = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationType }
     *     
     */
    public AnnotationType getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationType }
     *     
     */
    public void setAnnotation(AnnotationType value) {
        this.annotation = value;
    }

}
