//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 11:44:48 AM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.web;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for propType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="propType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="STRING"/>
 *     &lt;enumeration value="BOOLEAN"/>
 *     &lt;enumeration value="DECIMAL"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="DATE"/>
 *     &lt;enumeration value="URI"/>
 *     &lt;enumeration value="HTML"/>
 *     &lt;enumeration value="REFERENCE"/>
 *     &lt;enumeration value="WEAKREFERENCE"/>
 *     &lt;enumeration value="LONG"/>
 *     &lt;enumeration value="DOUBLE"/>
 *     &lt;enumeration value="BINARY"/>
 *     &lt;enumeration value="PATH"/>
 *     &lt;enumeration value="NAME"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum PropType {

    BINARY,
    BOOLEAN,
    DATE,
    DECIMAL,
    DOUBLE,
    HTML,
    INTEGER,
    LONG,
    NAME,
    PATH,
    REFERENCE,
    STRING,
    UNDEFINED,
    URI,
    WEAKREFERENCE;

    public String value() {
        return name();
    }

    public static PropType fromValue(String v) {
        return valueOf(v);
    }

}
