/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 10:53:39 AM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.web;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="propType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="STRING"/>
 *     &lt;enumeration value="BOOLEAN"/>
 *     &lt;enumeration value="DECIMAL"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="DATE"/>
 *     &lt;enumeration value="URI"/>
 *     &lt;enumeration value="HTML"/>
 *     &lt;enumeration value="REFERENCE"/>
 *     &lt;enumeration value="WEAKREFERENCE"/>
 *     &lt;enumeration value="LONG"/>
 *     &lt;enumeration value="DOUBLE"/>
 *     &lt;enumeration value="BINARY"/>
 *     &lt;enumeration value="PATH"/>
 *     &lt;enumeration value="NAME"/>
 *     &lt;enumeration value="UNDEFINED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "propType")
@XmlEnum
public enum PropType {

    STRING,
    BOOLEAN,
    DECIMAL,
    INTEGER,
    DATE,
    URI,
    HTML,
    REFERENCE,
    WEAKREFERENCE,
    LONG,
    DOUBLE,
    BINARY,
    PATH,
    NAME,
    UNDEFINED;

    public String value() {
        return name();
    }

    public static PropType fromValue(String v) {
        return valueOf(v);
    }

}
