//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 11:44:48 AM EEST 
//


package org.apache.stanbol.cmsadapter.servicesapi.model.web;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for property element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="property">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}localname"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}sourceObjectTypeRef"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}containerObjectRef" minOccurs="0"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}value" maxOccurs="unbounded"/>
 *           &lt;element ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}propertyDefinition" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute ref="{web.model.servicesapi.cmsadapter.stanbol.apache.org}type"/>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "localname",
    "sourceObjectTypeRef",
    "containerObjectRef",
    "value",
    "propertyDefinition"
})
@XmlRootElement(name = "property")
public class Property {

    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String localname;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected String sourceObjectTypeRef;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org")
    protected String containerObjectRef;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org", required = true)
    protected List<String> value;
    @XmlElement(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org")
    protected PropertyDefinition propertyDefinition;
    @XmlAttribute(namespace = "web.model.servicesapi.cmsadapter.stanbol.apache.org")
    protected PropType type;

    /**
     * Gets the value of the localname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalname() {
        return localname;
    }

    /**
     * Sets the value of the localname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalname(String value) {
        this.localname = value;
    }

    /**
     * Gets the value of the sourceObjectTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceObjectTypeRef() {
        return sourceObjectTypeRef;
    }

    /**
     * Sets the value of the sourceObjectTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceObjectTypeRef(String value) {
        this.sourceObjectTypeRef = value;
    }

    /**
     * Gets the value of the containerObjectRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerObjectRef() {
        return containerObjectRef;
    }

    /**
     * Sets the value of the containerObjectRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerObjectRef(String value) {
        this.containerObjectRef = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValue() {
        if (value == null) {
            value = new ArrayList<String>();
        }
        return this.value;
    }

    /**
     * Gets the value of the propertyDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyDefinition }
     *     
     */
    public PropertyDefinition getPropertyDefinition() {
        return propertyDefinition;
    }

    /**
     * Sets the value of the propertyDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyDefinition }
     *     
     */
    public void setPropertyDefinition(PropertyDefinition value) {
        this.propertyDefinition = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link PropType }
     *     
     */
    public PropType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropType }
     *     
     */
    public void setType(PropType value) {
        this.type = value;
    }

}
