package eu.iksproject.rick.servicesapi.yard;

import eu.iksproject.rick.servicesapi.Rick;
import eu.iksproject.rick.servicesapi.model.EntityMapping;
import eu.iksproject.rick.servicesapi.model.Representation;
import eu.iksproject.rick.servicesapi.model.Symbol;
import eu.iksproject.rick.servicesapi.site.ReferencedSite;
import eu.iksproject.rick.servicesapi.site.ReferencedSiteManager;



/**
 * <p>The Yard represents a local cache for {@link Representation}s of the Entities
 * and Symbols managed by a referenced site.<p>
 * </p>
 * <p> Referenced Sites need to provide the configuration if there representations
 * should be cached locally. This is done by using one of the defined {@link CacheStrategy}.
 * </p>
 * <p>The Idea is not to have one big Yard that caches all the representations, but
 * to provide the possibility to use different caches. This means, that each
 * {@link ReferencedSite} can have its own Yard instance. However
 * several Sites might also use the same Yard.</p>
 * <p>The {@link YardManager} is an singleton services that manages the different
 * Yard instances and provides an central point of access for the {@link Rick}
 * and the {@link ReferencedSiteManager}.</p>
 * <p> This should also allow for implementing Yards that are based on
 * <ul>
 * <li> Indexes generated by dumps of the referred Site</li>
 * <li> local installations of the software used by the referred site</li>
 * <li> and so on ... </li>
 * </ul>
 *
 * TODO: The framework need to provide something like a default Yord
 * TODO: The framework need to provide a special Yard for storing {@link Symbol}
 * and {@link EntityMapping} information.
 *
 * <p>Side note: The name yard was chosen because in farming the word "rick"
 * was used to describe small bales of Hay or Corn that are stacked in a
 * criss-crossed fashion. The word "rick yard" describes a farm-yard containing
 * ricks of hay or corn.</p>
 * @author Rupert Westenthaler
 *
 * TODO: Need to decide how Yards are linked to the Site for which they
 * cache entities.
 *
 */
public interface Yard {

    String ID = "eu.iksproject.rick.yard.id";
    String NAME = "eu.iksproject.rick.yard.name";
    String DESCRIPTION = "eu.iksproject.rick.yard.description";
    /**
     * Getter for the unique ID of the Yard (within the local rick node)
     * @return the id
     */
    String getId();
    String getName();
    String getDescription();
    /**
     * Creates a new representation. The Yard is responsible to assign a valid
     * ID.
     * @return the created Representation initialised with a valid ID
     */
    Representation create();
    /**
     * Creates a new representation for the given id
     * @param id the id for the new representation or <code>null</code> to
     * indicate that the Yard should assign an id.
     * @return the created Representation
     * @throws IllegalArgumentException if the parsed id is not valid or there
     * exists already a representation with the parsed id.
     */
    Representation create(String id) throws IllegalArgumentException;
    /**
     * Stores the representation in the Yard. if the parsed representation is
     * not present in the Yard it will add it to the Yard.
     * @param representation the representation
     * @throws IllegalArgumentException if <code>null</code> is parsed as argument or
     * the representation is not managed (e.g was not created by using this yard).
     */
    void store(Representation representation) throws IllegalArgumentException;
    /**
     * Removes the {@link Representation} with the given id
     * @param id the id
     * @throws IllegalArgumentException if the parsed ID is null or not valid
     * formatted
     */
    void remove(String id) throws IllegalArgumentException;
    /**
     * checks if a representation with the given id is present in the Yard
     * @param id the id. Calls with <code>null</code> are ignored
     * @return <code>true</code> if a representation with the id is present in
     * the Yard. Otherwise <code>false</code>.
     * @throws IllegalArgumentException if the parsed ID is not valid
     * formatted
     */
    boolean isRepresentation(String id);
    /**
     * Getter for the representation based on the id. Calls with
     * <code>id = null</code> should return null.
     * @param id the id.
     * @return The representation with the parsed id or <code>null</code> if
     * no representation with this id is present in the Yard
     * @throws IllegalArgumentException if the parsed ID is not valid
     * formatted
     */
    Representation getRepresentation(String id);
    /**
     * Updates the store with the new state of the parsed representation
     * @param represnetation the representation
     * @throws IllegalArgumentException if the parsed representation <code>null</code>
     * or not present in the Yard
     */
    void update(Representation represnetation) throws IllegalArgumentException;

/*
 * TODO: Maybe one would like to add status Information about cached
 *       Representations for registered Sites.
 */
// enum ProcessingStatus {
//        scheduled,
//        processing,
//        stored
//    };
//    ProcessingStatus getStatus(Site site);
//    ProcessingStatus getStatus(String entityId);
}
