package org.apache.stanbol.reengineer.db.ontology;

/* CVS $Id: Schema.java 1082603 2011-03-17 17:41:13Z alexdma $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://andriry.altervista.org/tesiSpecialistica/schema.owl 
 * @author Auto-generated by schemagen on 07 Jul 2010 17:13 
 */
public class Schema {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Resource Annotation = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Annotation" );
    
    public static final Resource Any = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Any" );
    
    public static final Resource AnyAttribute = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#AnyAttribute" );
    
    public static final Resource Appinfo = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Appinfo" );
    
    public static final Resource Attribute = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Attribute" );
    
    public static final Resource AttributeGroup = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#AttributeGroup" );
    
    public static final Resource Choice = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Choice" );
    
    public static final Resource ComplexContent = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#ComplexContent" );
    
    public static final Resource ComplexType = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#ComplexType" );
    
    public static final Resource Documentation = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Documentation" );
    
    public static final Resource Element = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Element" );
    
    public static final Resource Enumeration = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Enumeration" );
    
    public static final Resource Extension = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Extension" );
    
    public static final Resource Field = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Field" );
    
    public static final Resource FractionDigits = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#FractionDigits" );
    
    public static final Resource Group = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Group" );
    
    public static final Resource HasFacet = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#HasFacet" );
    
    public static final Resource HasFacetAndPropertyhasProperty = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#HasFacetAndPropertyhasProperty" );
    
    public static final Resource Import = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Import" );
    
    public static final Resource Key = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Key" );
    
    public static final Resource List = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#List" );
    
    public static final Resource MaxEclusive = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#MaxEclusive" );
    
    public static final Resource MinEclusive = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#MinEclusive" );
    
    public static final Resource MaxInclusive = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#MaxInclusive" );
    
    public static final Resource MinInclusive = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#MinInclusive" );
    
    public static final Resource MinLength = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#MinLength" );
    
    public static final Resource Notation = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Notation" );
    
    public static final Resource Pattern = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Pattern" );
    
    public static final Resource All = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#All" );
    
    public static final Resource Restriction = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Restriction" );
    
    public static final Resource Schema = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Schema" );
    
    public static final Resource Selector = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Selector" );
    
    public static final Resource Sequence = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Sequence" );
    
    public static final Resource SimpleType = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#SimpleType" );
    
    public static final Resource Union = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Union" );
    
    public static final Resource WhiteSpace = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#WhiteSpace" );
    
    public static final Resource ScopeAbsent = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Absent" );
    
    public static final Resource ScopeLocal = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Local" );
    
    public static final Resource ScopeGlobal = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#Global" );
    
    public static final Resource VC_NONE = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#VC_NONE" );
    
    public static final Resource VC_DEFAULT = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#VC_DEFAULT" );
    
    public static final Resource VC_FIXED = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#VC_FIXED" );
    
    public static final Resource DERIVATION_EXTENSION = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#DERIVATION_EXTENSION" );
    
    public static final Resource DERIVATION_RESTRICTION = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#DERIVATION_RESTRICTION" );
    
    public static final Resource DERIVATION_NONE = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#DERIVATION_NONE" );
    
    public static final Resource PROHIBITED_EXTENSION = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#PROHIBITED_EXTENSION" );
    
    public static final Resource PROHIBITED_RESTRICTION = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#PROHIBITED_RESTRICTION" );
    
    public static final Resource PROHIBITED_NONE = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#PROHIBITED_NONE" );
    
    public static final Resource COLLAPSE = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#COLLAPSE" );
    
    public static final Resource PRESERVE = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#PRESERVE" );
    
    public static final Resource REPLACE = m_model.createResource( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#REPLACE" );
    
    public static final Property abstractProperty = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#abstract" );
    
    public static final Property name = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#name" );
    
    public static final Property type = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#type" );
    
    public static final Property hasScope = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasScope" );
    
    public static final Property hasConstraintType = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasConstraintType" );
    
    public static final Property hasFinal = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasFinal" );
    
    public static final Property constraint = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#constraint" );
    
    public static final Property maxOccurs = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#maxOccurs" );
    
    public static final Property minOccurs = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#minOccurs" );
    
    public static final Property hasProhibitedSubstitutions = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasProhibitedSubstitutions" );
    
    public static final Property required = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#required" );
    
    public static final Property hasParticle = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasParticle" );
    
    public static final Property hasCompositor = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasCompositor" );
    
    public static final Property value = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#value" );
    
    public static final Property hasEnumeration = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasEnumeration" );
    
    public static final Property hasWhitespace = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasWhitespace" );
    
    public static final Property base = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#base" );
    
    public static final Property hasAnnotation = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasAnnotation" );
    
    public static final Property hasPattern = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasPattern" );
    
    public static final Property hasAttributeUse = m_model.createProperty( "http://andriry.altervista.org/tesiSpecialistica/schema.xsd#hasAttributeUse" );
    
}
